###################################################################
# Spins up a 3-node Redpanda cluster with self-signed certificates
###################################################################
---
version: "3.7"
name: redpanda-doom

networks:
  redpanda_network:
    driver: bridge

secrets:
  broker_key:
    file: ./broker.key

services:
  redpanda-0:
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda-0:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr internal://redpanda-0:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --rpc-addr redpanda-0:33145
      - --advertise-rpc-addr redpanda-0:33145
      - --smp 4
      - --memory 4G
      - --default-log-level=info
    image: docker.redpanda.com/redpandadata/redpanda:v23.1.10
    container_name: redpanda-0
    volumes:
      - type: tmpfs
        target: /var/lib/redpanda/data
    networks:
      - redpanda_network
    ports:
      - 18081:18081
      - 18082:18082
      - 19092:19092
      - 19644:9644
    secrets:
      - broker_key

  flink-jobmanager:
    command: jobmanager
    image: flink:1.17
    networks:
      - redpanda_network
    ports:
      - 8081:8081
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager

  flink-taskmanager-0:
    command: taskmanager
    image: flink:1.17
    networks:
      - redpanda_network
    depends_on:
      - flink-jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.numberOfTaskSlots: 4
        taskmanager.memory.process.size: 4g
        parallelism.default: 1

  console:
    container_name: redpanda-console
    image: docker.redpanda.com/redpandadata/console:v2.2.3
    networks:
      - redpanda_network
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda-0:9092"]
          clientId: console
          schemaRegistry:
            enabled: true
            urls: ["http://redpanda-0:8081"]
          sasl:
            enabled: true
            username: admin
            password: password
            mechanism: SCRAM-SHA-256
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda-0:9644"]
    ports:
      - 8080:8080
    depends_on:
      - redpanda-0
    volumes:
      - "./ca.crt:/tls/ca.crt:ro"
